[package]
name = "wake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.26"
sea-orm = "0.11.3"
serde = "1.0.164"
tokio = "1.28.2"
tower-http = "0.4.1"
