FROM centos:7.6.1810

RUN yum -y update && yum clean all
RUN yum --setopt=skip_missing_names_on_install=False install -y epel-release
RUN yum --setopt=skip_missing_names_on_install=False install -y \
  git \
  which \
  make \
  gcc \
  gcc-c++ \
  fuse-devel \
  gmp-devel \
  ncurses-devel \
  sqlite-devel \
  re2-devel

WORKDIR /build
COPY . /build

RUN USE_FUSE_WAKE=0 make install
