FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  build-essential \
  git \
  libfuse-dev \
  libgmp-dev \
  libncurses5-dev \
  libre2-dev \
  libsqlite3-dev \
  pkg-config
WORKDIR /build
COPY . /build
RUN USE_FUSE_WAKE=0 make install
