# Track the newest software available and detect problems early!
FROM debian:testing

RUN apt-get update && apt-get install -y \
  build-essential \
  devscripts \
  git \
  libfuse-dev \
  libgmp-dev \
  libncurses5-dev \
  libre2-dev \
  libsqlite3-dev \
  pkg-config

WORKDIR /build
COPY . /build

RUN USE_FUSE_WAKE=0 make wake.db
RUN USE_FUSE_WAKE=0 ./bin/wake tarball Unit
RUN tar xvJf wake_*.tar.xz && cd wake-* && debuild -us -uc
