FROM centos:6.6

RUN yum -y update && yum clean all
RUN yum --setopt=skip_missing_names_on_install=False install -y epel-release centos-release-scl
RUN yum --setopt=skip_missing_names_on_install=False install -y \
  git \
  which \
  make \
  devtoolset-6-gcc \
  devtoolset-6-gcc-c++ \
  fuse-devel \
  gmp-devel \
  ncurses-devel \
  sqlite-devel \
  re2-devel

WORKDIR /build
COPY . /build

SHELL [ "/usr/bin/scl", "enable", "devtoolset-6" ]
RUN USE_FUSE_WAKE=0 make install
