#! /bin/sh

# "${1}/wake-format" $(cat ./srclist.txt) > /dev/null

"${1}/wake-format" ../../../extensions/vscode/vscode.wake > /dev/null
"${1}/wake-format" ../../../tools/shim-wake/shim.wake > /dev/null
"${1}/wake-format" ../../../tools/job-cache/job-cache.wake > /dev/null
"${1}/wake-format" ../../../tools/bsp-wake/bsp.wake > /dev/null
"${1}/wake-format" ../../../tools/wake/wake.wake > /dev/null
"${1}/wake-format" ../../../tools/fuse-waked/fuse-waked.wake > /dev/null
"${1}/wake-format" ../../../tools/lsp-wake/lsp.wake > /dev/null
"${1}/wake-format" ../../../tools/wake-format/wake-format.wake > /dev/null
"${1}/wake-format" ../../../tools/wake-unit/wake-unit.wake > /dev/null
"${1}/wake-format" ../../../tools/wakebox/wakebox.wake > /dev/null
"${1}/wake-format" ../../../tools/tools.wake > /dev/null
"${1}/wake-format" ../../../tests/runtime/symlinks/test.wake > /dev/null
"${1}/wake-format" ../../../tests/standard-library/groupBy/test.wake > /dev/null
"${1}/wake-format" ../../../tests/parser/unicode/test.wake > /dev/null
"${1}/wake-format" ../../../tests/type-system/require-pass/test.wake > /dev/null
"${1}/wake-format" ../../../tests/type-system/match-pass/test.wake > /dev/null
"${1}/wake-format" ../../../tests/type-system/extract-pass/test.wake > /dev/null
"${1}/wake-format" ../../../tests/type-system/lambda-pass/test.wake > /dev/null
"${1}/wake-format" ../../../tests/type-system/value-restriction/test.wake > /dev/null
"${1}/wake-format" ../../../tests/standard-library/json-normalize-merge/json-test.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/versions/v0_27.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/versions/v0_24.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/versions/v0_28.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/nothing/nothing.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/option.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/syntax.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/integer.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/regexp.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/types.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/boolean.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/result.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/tuple.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/double.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/order.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/print.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/system/environment.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/gcc_wake/pkgconfig.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/gcc_wake/gcc.wake > /dev/null > /dev/null
"${1}/wake-format" ../../../vendor/blake2/blake2.wake > /dev/null
"${1}/wake-format" ../../../vendor/utf8proc/utf8proc.wake > /dev/null
"${1}/wake-format" ../../../vendor/fuse.wake > /dev/null
"${1}/wake-format" ../../../vendor/whereami/whereami.wake > /dev/null
"${1}/wake-format" ../../../vendor/gopt/gopt.wake > /dev/null
"${1}/wake-format" ../../../vendor/lemon/lemon.wake > /dev/null
"${1}/wake-format" ../../../vendor/sqlite3.wake > /dev/null
"${1}/wake-format" ../../../vendor/gmp.wake > /dev/null
"${1}/wake-format" ../../../vendor/re2.wake > /dev/null
"${1}/wake-format" ../../../vendor/vendor.wake > /dev/null
"${1}/wake-format" ../../../vendor/emscripten.wake > /dev/null
"${1}/wake-format" ../../../vendor/git.wake > /dev/null
"${1}/wake-format" ../../../vendor/ncurses.wake > /dev/null
"${1}/wake-format" ../../../vendor/siphash/siphash.wake > /dev/null
"${1}/wake-format" ../../../build.wake > /dev/null
"${1}/wake-format" ../../../src/compat/compat.wake > /dev/null
"${1}/wake-format" ../../../src/json/json.wake > /dev/null
"${1}/wake-format" ../../../src/dst/dst.wake > /dev/null
"${1}/wake-format" ../../../src/parser/parser.wake > /dev/null
"${1}/wake-format" ../../../src/optimizer/optimizer.wake > /dev/null
"${1}/wake-format" ../../../src/types/types.wake > /dev/null
"${1}/wake-format" ../../../src/runtime/runtime.wake > /dev/null
"${1}/wake-format" ../../../src/wcl/wcl.wake > /dev/null
"${1}/wake-format" ../../../src/src.wake > /dev/null
"${1}/wake-format" ../../../src/util/util.wake > /dev/null
"${1}/wake-format" ../../../src/wakefs/wakefs.wake > /dev/null
"${1}/wake-format" ../../../vendor/re2c.wake > /dev/null
"${1}/wake-format" ../../../tests/type-system/multi-match-pass/test.wake > /dev/null
"${1}/wake-format" ../../../tests/tests.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/map.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/vector.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/string.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/system/sources.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/system/path.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/json.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/list.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/core/tree.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/system/job.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/system/incremental.wake > /dev/null
"${1}/wake-format" ../../../share/wake/lib/system/io.wake > /dev/null
