#define TOKEN_WS                               1
#define TOKEN_COMMENT                          2
#define TOKEN_P_BOPEN                          3
#define TOKEN_P_BCLOSE                         4
#define TOKEN_P_SOPEN                          5
#define TOKEN_P_SCLOSE                         6
#define TOKEN_ID                               7
#define TOKEN_NL                               8
#define TOKEN_INDENT                           9
#define TOKEN_DEDENT                          10
#define TOKEN_KW_PACKAGE                      11
#define TOKEN_KW_FROM                         12
#define TOKEN_KW_IMPORT                       13
#define TOKEN_P_HOLE                          14
#define TOKEN_KW_EXPORT                       15
#define TOKEN_KW_DEF                          16
#define TOKEN_KW_TYPE                         17
#define TOKEN_KW_TOPIC                        18
#define TOKEN_KW_UNARY                        19
#define TOKEN_KW_BINARY                       20
#define TOKEN_P_EQUALS                        21
#define TOKEN_OP_DOT                          22
#define TOKEN_OP_QUANT                        23
#define TOKEN_OP_EXP                          24
#define TOKEN_OP_MULDIV                       25
#define TOKEN_OP_ADDSUB                       26
#define TOKEN_OP_COMPARE                      27
#define TOKEN_OP_INEQUAL                      28
#define TOKEN_OP_AND                          29
#define TOKEN_OP_OR                           30
#define TOKEN_OP_DOLLAR                       31
#define TOKEN_OP_LRARROW                      32
#define TOKEN_OP_EQARROW                      33
#define TOKEN_OP_COMMA                        34
#define TOKEN_KW_GLOBAL                       35
#define TOKEN_P_COLON                         36
#define TOKEN_KW_PUBLISH                      37
#define TOKEN_KW_DATA                         38
#define TOKEN_KW_TUPLE                        39
#define TOKEN_KW_TARGET                       40
#define TOKEN_P_BSLASH                        41
#define TOKEN_P_POPEN                         42
#define TOKEN_P_PCLOSE                        43
#define TOKEN_STR_RAW                         44
#define TOKEN_STR_SINGLE                      45
#define TOKEN_STR_MID                         46
#define TOKEN_STR_OPEN                        47
#define TOKEN_STR_CLOSE                       48
#define TOKEN_MSTR_CONTINUE                   49
#define TOKEN_MSTR_BEGIN                      50
#define TOKEN_MSTR_END                        51
#define TOKEN_MSTR_PAUSE                      52
#define TOKEN_MSTR_MID                        53
#define TOKEN_MSTR_RESUME                     54
#define TOKEN_LSTR_CONTINUE                   55
#define TOKEN_LSTR_BEGIN                      56
#define TOKEN_LSTR_END                        57
#define TOKEN_LSTR_PAUSE                      58
#define TOKEN_LSTR_MID                        59
#define TOKEN_LSTR_RESUME                     60
#define TOKEN_REG_SINGLE                      61
#define TOKEN_REG_MID                         62
#define TOKEN_REG_OPEN                        63
#define TOKEN_REG_CLOSE                       64
#define TOKEN_DOUBLE                          65
#define TOKEN_INTEGER                         66
#define TOKEN_KW_HERE                         67
#define TOKEN_KW_SUBSCRIBE                    68
#define TOKEN_KW_PRIM                         69
#define TOKEN_KW_MATCH                        70
#define TOKEN_KW_IF                           71
#define TOKEN_KW_THEN                         72
#define TOKEN_KW_ELSE                         73
#define TOKEN_KW_REQUIRE                      74
