#! /bin/sh
set -xe

# eg: https://6075-148184315-gh.circle-artifacts.com/0/tmp/workspace/release
url="$1"

# eg: 0.18.1
version="$2"

curl -L -o wake_${version}.tar.xz                      ${url}/wake_${version}.tar.xz
curl -L -o wake-${version}.vsix                        ${url}/vscode/wake-${version}.vsix
curl -L -o wake-static_${version}.tar.xz               ${url}/alpine/wake-static_${version}.tar.xz
curl -L -o rocky_8-wake-${version}-1.x86_64.rpm        ${url}/rocky_8/wake-${version}-1.x86_64.rpm
curl -L -o debian-bullseye-wake_${version}-1_amd64.deb ${url}/debian_bullseye/wake_${version}-1_amd64.deb
curl -L -o ubuntu-18-04-wake_${version}-1_amd64.deb    ${url}/ubuntu_18_04/wake_${version}-1_amd64.deb
curl -L -o ubuntu-22-04-wake_${version}-1_amd64.deb    ${url}/ubuntu_22_04/wake_${version}-1_amd64.deb
