#! /bin/bash

HERE="$( dirname -- "${0}"; )"
WAKE_ROOT="${HERE}/../"

if [[ ${1} == "all" ]]; then
  SOURCE_FILES=$(find ${WAKE_ROOT} -type f \( -name "*.h" -o -name "*.cpp" -o -name "*.c" \) | grep -v 'vendor')

  echo $SOURCE_FILES

  # Flag if any files were found
  if [ "$SOURCE_FILES" ]; then
    exit 0
  fi
  exit 1
fi

if [[ ${1} == "changed" ]]; then
  CHANGED_FILES=$(git --git-dir ${WAKE_ROOT}.git diff --name-only | grep '\.h\|\.cpp\|\.c' | grep -v 'vendor/')
  STAGED_FILES=$(git --git-dir ${WAKE_ROOT}.git diff --name-only --cached | grep '\.h\|\.cpp\|\.c' | grep -v 'vendor/')
  MERGED="${CHANGED_FILES} ${STAGED_FILES}"
  
  echo ${MERGED}

  # Flag if any files were found
  if [ "${MERGED}" ]; then
    exit 0
  fi
  exit 1
fi

echo "unknown parameter: '${1}'"
exit 1
