= Creating a new release of Wake

The following describes the steps for creating a new release of Wake and publishing the artifacts to GitHub.

1. Update to the lastest version of `master`
+
[source,shell]
----
$ git checkout master
$ git pull origin master
----

2. Create a branch to update the release info, e.g. `release-0.15.3`.
+
[source,shell]
----
$ git checkout -b release-0.15.3
----

3. Open `debian/changelog.in` in a text editor.
   Check to see whether the top-most release note corresponds to the previous release or whether it is a placeholder for the next release.
   If you see the previous release's version number in the release note second from the top, then the top-most release note is a placeholder for the next release. In this case, go to step 5.
   If instead it looks like the top-most release _is_ the previous release, then go to step 4.

4. Create a copy of the top-most release note immediately below it.
   In the second instance, replace the `@VERSION@` string with the actual version number of the previous release.

5. Update the top-most release note to contain the actual release information.
   Update the text to describe the release itself.
   Update the author, email, and the release date to match the actual release information.

6. Commit the changes to `changelog.in`.
+
[source,shell]
----
$ git add debian/changelog.in
$ git commit -m "Set release date."
----

7. Push the branch to GitHub.
+
[source,shell]
----
$ git push origin release-0.15.3
----

8. Open a pull request on GitHub. Make sure you set the base branch to `master`.

9. Merge the release into master after CI passses and PR is approved.

10. Checkout master and update to the release commit
+
[source,shell]
----
$ git checkout master
$ git pull origin master
----

11. Create a tag with the version string you want to use, e.g. `v0.15.3`, and push the tag to GitHub.
+
[source,shell]
----
$ git tag v0.15.3
$ git push origin v0.15.3
----

12. After the tagged is pushed, the release workflow will automatically generate a GitHub draft release.
    Wait for the release to be created then download the vsix artifact and upload it to the MS marketplace
    The update link is here: https://marketplace.visualstudio.com/manage/publishers/sifive

13. Finalize the release copy and publish.
